# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-SSH-Perl
version:      1.25
version_from: lib/Net/SSH/Perl.pm
installdirs:  site
requires:
    Crypt::Blowfish:               0
    Crypt::DES:                    0
    Crypt::IDEA:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
